### ISSUE TITLE
Issue Accessing .ipynb Notebooks in the Repository

### ISSUE THREAD

**Issue by derrick-daniel** [Lightning-AI/dl-fundamentals#111]
**Error Message:** "An error occurred" when trying to view `.ipynb` files directly on GitHub.

**Steps to Reproduce:**
1. Go to the `unit01-ml-intro` directory in the repository.
2. Click on `perceptron-part1.ipynb`.
3. Notice the error preventing the notebook from being displayed.

A similar issue has been discussed on Stack Overflow here: [Stack Overflow Discussion](https://stackoverflow.com/questions/78507035/how-can-i-render-my-project-on-github-i-am-receiving-error-an-error-occurred-u#comment138404343_78507035).

Thank you for your attention to this matter.

**Comment by rasbt** [comment]
Hi there, and thanks for reporting!

this is unfortunately a GitHub issue that occurred since weekend and affects all notebooks on GitHub (not just this one): https://github.com/orgs/community/discussions/124651

In the meantime, until GitHub fixes it, you can paste the link into https://nbviewer.org, which renders the docs correctly.

**Comment by rasbt** [comment]
It seems like GitHub solved the issue a few hours ago. It should be working fine now again 😊
